        <footer>
            &copy; Copyright s4007562 Scarlett. All Rights Reserved | Designed for GAMESRUs
        </footer>
        <details open>
            <summary>Debug Info</summary>
            <h4>GET</h4>
            <?php
            preshow($_GET);
            ?>

            <h4>POST</h4>
            <?php 
            preshow($_POST);
            ?>

            <h4>
                SESSION
            </h4>
            <?php
            ?>
        </details>
    </div>

</body>

</html>