<!-- nav.inc --->
<nav>
  <a href="index.php">
    <img height="40" src="images/logo.png" alt="GAMESRUS Logo" />
  </a>
  <select onchange="navigateToPage(this)">
    <option value="" selected disabled>Select an Option...</option>
    <option value="index.php">Home</option>
    <option value="games.php">Games</option>
    <option value="add.php">Add More</option>
    <option value="gallery.php">Gallery</option>
  </select>
</nav>
